lab3a:	lab3a.c
	gcc -g -Wall -o lab3a -std=c99 lab3a.c
clean:
	rm lab3a super.csv bitmap.csv directory.csv group.csv inode.csv indirect.csv
dist:
	tar -czf lab3a-104485521.tar.gz lab3a.c README Makefile
