lab2b:	lab2b.c SortedList.c
	gcc -pthread -g -Wall -o lab2b lab2b.c SortedList.c

clean:
	rm lab2b

dist:
	tar -czf lab2b-104485521.tar.gz lab2b.c SortedList.h SortedList.c Makefile README graph1.png graph2.png
